In [3]:
import pandas as pd

df = pd.read_csv(r"preprocessing_datasets\01_missingness_mechanisms.csv")

print(df.info())
print("\n--- DESCRIBE ---")
print(df.describe(include="all"))

print("\n--- MISSING VALUES ---")
print(df.isnull().sum())

print("\n--- DATA ---")
display(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         10 non-null     int64
 1   age        10 non-null     int64
 2   income     7 non-null      float64
 3   purchased  10 non-null     object
dtypes: float64(1), int64(2), object(1)
memory usage: 448.0+ bytes
None

--- DESCRIBE ---
              id        age        income purchased
count   10.00000  10.000000      7.000000        10
unique       NaN        NaN           NaN         2
top          NaN        NaN           NaN       Yes
freq         NaN        NaN           NaN         6
mean     5.50000  42.200000  64571.428571       NaN
std      3.02765  12.461496  17328.753974       NaN
min      1.00000  25.000000  45000.000000       NaN
25%      3.25000  31.750000  54500.000000       NaN
50%      5.50000  43.000000  61000.000000       NaN
75%      7.75000  49.250000  69500.000000       NaN
max     10.00000  62.000000  98000.000000       NaN

--- MISSING VALUES ---
id           0
age          0
income       3
purchased    0
dtype: int64

--- DATA ---

   id  age   income purchased
0   1   25  45000.0        No
1   2   34  51000.0       Yes
2   3   58      NaN        No
3   4   29      NaN       Yes
4   5   62      NaN        No
5   6   41  98000.0       Yes
6   7   47  67000.0       Yes
7   8   50  72000.0       Yes
8   9   45  61000.0        No
9  10   31  58000.0       Yes

In [4]:
df[df["income"].isna()]

   id  age  income purchased
2   3   58     NaN        No
3   4   29     NaN       Yes
4   5   62     NaN        No